### ISSUE TITLE
Can't add widgets from panel with Sweet SDDM login screen enabled

### ISSUE THREAD

**Issue by Privacy-Badger-User** [EliverLara/Sweet-kde#10]
I am using your beautiful theme for Global, Plasma Style, Window Decorations, Colors and Icons in Plasma 5.18.3 under Tumbleweed 20200326.  When I also try to use the Sweet login screen, unfortunately, I run into a problem: after logging in, I am unable to add widgets to the panel.  I click 'Add Widgets,' and nothing happens.

Reverting to the Breeze Login Screen fixed the problem.  

Thanks for your great work on a magnificent theme!

**Comment by EliverLara** [comment]
Hi, I use the sddm theme as my default and I have not faced that issue, Does this happen with another theme?

**Comment by Privacy-Badger-User** [comment]
The problem is temperamental.  I'm in the middle of a big configuration project now, and had the chance to apply your excellent theme to two more KDE installations on two other computers.  I usually do **not** have the problem if I don't change the background of your login screen.  On the other hand, I usually **do** have it if I change the background.  

That said, if I log out and log back in again, "add widgets" magically works again.   Odd!

I don't change widgets often, and logging out/logging in isn't much trouble.  Other login screens I downloaded were much buggier.  I'm happy to be able to use your theme, and am not surprised that it's so highly rated at the KDE store.
