### ISSUE TITLE
Not able to configure the background of Application Launcher

### ISSUE THREAD

**Issue by Geeky-nutcracker** [EliverLara/Sweet-kde#13]
Been using this theme for 2 days as of now but I was unable to figure out how would I be able to configure the background of the Application manager which is translucent in nature. I tried to change values within metadata.desktop but it was of no use. So kindly tell me how would I be able to change the transparency according to my willingness
![VirtualBox_Noru_31_03_2020_12_05_11](https://user-images.githubusercontent.com/62972573/78090123-e29f8980-73e6-11ea-8117-8c1e368dc0ef.png)

**Comment by EliverLara** [comment]
Hi, to change that you must edit the `Sweet/dialogs/background.svgz `file
