### ISSUE TITLE
Very dark text on a dark grey background in the panel

### ISSUE THREAD

**Issue by Peter-Levine** [EliverLara/Sweet-kde#15]
![Screenshot_20200522_010029](https://user-images.githubusercontent.com/15844843/82632949-cb4f7200-9bc7-11ea-9d0a-0421416ec8e5.png)

This issue has existed ever since I first tried Sweet-KDE, with multiple KDE versions.  The color theme is fine with the exception of the panel, whose text is barely discernable.  Changing the color scheme has no effect.  Logging out/rebooting has no effect.  Only changing the plasma style to something other than Sweet fixes it.

**Comment by EliverLara** [comment]
Hi, what is your version of plasma?

**Comment by Peter-Levine** [comment]
Operating System: Gentoo 
KDE Plasma Version: 5.18.90
KDE Frameworks Version: 5.70.0
Qt Version: 5.14.2
Kernel Version: 5.6.13-gentoo
OS Type: 64-bit
Processors: 8 × Intel® Core™ i7-7700HQ CPU @ 2.80GHz
Memory: 31.1 GiB of RAM
Graphics Processor: Mesa Intel® HD Graphics 630

**Comment by Peter-Levine** [comment]
After testing some values with those of other themes it seems that the offending setting is in _.local/share/plasma/desktoptheme/Sweet/colors_, 
```
[Colors:Window]
ForegroundNormal=#D9DD
```
If I change _ForegroundNormal_ to a value like `188,188,178`, for instance, and reload the theme, the issue disappears.

**Comment by Peter-Levine** [comment]
So it seems that colors expressed in hex format look different that colors expressed in their RGB equivalents.  The equivalent of `#D9DDE3` is `217,221,227`.  When I change `ForegroundNormal` to the RGB version, the issue is fixed.

**Comment by Peter-Levine** [comment]
Sorry.  The problem was on my end.  After rebuilding my system with safe CFLAGS/CXXFLAGS the problem disappeared.
