### ISSUE TITLE
Scaling issue on title bar

### ISSUE THREAD

**Issue by festie** [EliverLara/Sweet-kde#2]
Hey,

I love this theme, but unfortunately it doesn't work well for me:
![grafik](https://user-images.githubusercontent.com/6287093/58923409-e9665d00-873f-11e9-8e8d-d23a40e0e88a.png)

If you take a closer look, you can see that the full title bar is transparent, but it's actually missing the radius, so simply modifying the sweet-darkrc file won't fix anything.

I'm using a default 1080p monitor with a 4k monitor. The 4k monitor is set to 1080p as well and both have a scaling of 1 set in KDE. This also happens when the 4k monitor is completely disconnected.

Previously I've found these two threads but they didn't help me in any way:
- https://www.reddit.com/r/kde/comments/7n7snq/plasma_window_titlebar_is_messed_up_when_using/
- https://forum.manjaro.org/t/kde-plasma-title-bar-decorator-issue/43569/8

What details do you need and where do I get them?
(OT: What have you done to make dolphin look like how it looks with the icons on the left?)

**Comment by festie** [comment]
Okey, nvm. After googling a lot more I found this reply in your other repo:
https://github.com/EliverLara/Sweet/issues/34

As stated there, forcing the Font DPI to 96 fixed the issue after restarting the display-manager (`sudo systemctl restart display-manager`).

**Comment by EliverLara** [comment]
Thank you so much for providing a solution.

About dolphin view:

- Right click on toolbar > Text position > only icons
- Uncheck the 'Lock toolbar position' option and drag it to where you need it
