### ISSUE TITLE
Global Menu on Hover style look bad

### ISSUE THREAD

**Issue by hsnfirdaus** [EliverLara/Sweet-kde#30]
![Screenshot_10](https://user-images.githubusercontent.com/38871578/122400427-e694d880-cfa5-11eb-9ec9-c49d174ba791.png)
When i'm hovering my global menu the text background is white and the text color is light grey, so it can not be read... I'm using default Garuda dragonized theme in KDE...

**Comment by dr460nf1r3** [comment]
Adding some information to this: 
The default theme is basically using the Sweet theme with a different icon pack & global layout. The appmenu itself is provided by this [applet](https://github.com/psifidotos/applet-window-appmenu).

**Comment by nisarr** [comment]
@hsnfirdaus Edit the panel and change the colors to "Layout custom colors". It will change the background color to dark depending on the layout color setting.
