### ISSUE TITLE
issue with margins seperator.

### ISSUE THREAD

**Issue by TheNukeLore** [EliverLara/Sweet-kde#45]
When using the margins separator on a panel, no margin separation is applied while it does on other themes.

Sweet kde:
![image](https://github.com/EliverLara/Sweet-kde/assets/56121120/35be75a5-5ae5-414c-bec0-5e9166aa2672)

Breeze: 
![image](https://github.com/EliverLara/Sweet-kde/assets/56121120/d0143817-2aa6-4ff5-abc2-20547a74cc03)

**Comment by TheNukeLore** [comment]
not good in this area but looking into it, appears its regarding the panel-background.svg in widgets if that helps at all(or if this theme is even still actively maintained)

**Comment by EliverLara** [comment]
Hi, Do you mean that indicator is missing?

![sweet_indicator_issue](https://github.com/EliverLara/Sweet-kde/assets/9838260/f42055f0-967c-453a-89a3-9d4b29c44338)

**Comment by EliverLara** [comment]
Fixed with 1d0d50466e6055a98a5efcca79d3398a33c15ea1
