### ISSUE TITLE
Installation on KDE

### ISSUE THREAD

**Issue by Eliyanan** [EliverLara/Sweet-kde#5]
Hello there, is this theme the same with the one found when searching in kde look and feel setting? because I downloaded the theme from the setting but the blur thing is not working properly. 
So if this is different from that how can I manually install this one please...
![photo_2019-11-13_09-34-31](https://user-images.githubusercontent.com/17715731/68739029-e75ecf00-05f8-11ea-90e1-e3b8a274707e.jpg)

**Comment by Eliyanan** [comment]
look at the background of the terminal, the blur thing is not working properly, as I said the theme is downloaded from look and feel setting

**Comment by EliverLara** [comment]
Hi, why do you say blur is not working properly?

**Comment by Eliyanan** [comment]
'cause it is not working properly, check the pic I had attached, and the background of the terminal is  not right. I am using KDE,and I had installed sweet theme from look and feel search bar. Not from here!

**Comment by EliverLara** [comment]
I think you're talking about the pixelated blur, if so, it's easily customizable on kde settings `system preferences > desktop behaviour > desktop effects > blur `

**Comment by Eliyanan** [comment]
Thank you so much I reduced the noise of the blur now it get fixed!
