### ISSUE TITLE
Can't login by typing password followed by return.

### ISSUE THREAD

**Issue by PartialVolume** [EliverLara/Sweet-kde#7]
I did an update last night of KDE Neon, currently at 5.17.4 and I find that if I try to login by typing the password followed by a carriage return nothing happens. I need to click with the mouse the symbol to the right of the password field to login. Prior to the KDE Neon update I could type the login password and hit return.

Forums suggest the KDE update probably broke something in Sweet-kde. Is that possible ?

**Comment by EliverLara** [comment]
Hi, Are you using the sweet-sddm theme?

**Comment by PartialVolume** [comment]
I wasn't, upon checking I was using Breeze, I've now installed sweet-sddm for login and I'll get back to you with the results. I'm guessing it probably isn't a sweet issue.

BTW, thanks for the theme, very nice !. The only thing I would change is to lighten the borders in some way so they stand out, sometimes it can be tricky to find where one window starts and another ends when it's all dark. :-)

**Comment by PartialVolume** [comment]
How strange, the screen lock suffers from the same problem, however if I change the locking screen backdrop to a photo then the password responds to a carriage return but for subsequent password attempts the return key doesn't work, then change the backdrop of the lock screen and then the return key works the first time you try it but not on subsequent attempts. So I don't think it's a sweet-kde problem but something else ?

**Comment by PartialVolume** [comment]
On further checking, whether the login responds to the carriage return seems to be just random. (The actual keyboard hardware is ok as the return key works normally in other software).

**Comment by EliverLara** [comment]
Does this still persist?

**Comment by PartialVolume** [comment]
Yes, the problem is still present. There is a Issue open on https://github.com/sddm/sddm/issues/1215 that goes into more detail.
