### ISSUE TITLE
Theme installed but now showing in Look and Feel

### ISSUE THREAD

**Issue by fsevenm** [EliverLara/Sweet-kde#9]
I've installed this theme via System Settings and installed successfully but, it seems like the theme does not apper in Look and Feel options. Any solutions?

**Edit:**
I am on Kubuntu 19.10

**Comment by EliverLara** [comment]
Hi, did you try reinstalling it?

**Comment by fsevenm** [comment]
I tried to install it from Discover  and now it appears on Look and Feel settings
